// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TimeKeeper.Models
{
    public partial class Empleados
    {
        public Empleados()
        {
            Tiempos = new HashSet<Tiempos>();
        }

        public int IdEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Departamento { get; set; }
        public bool HasImg { get; set; }

        public virtual ICollection<Tiempos> Tiempos { get; set; }
    }
}