// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TimeKeeper.Models;

namespace TimeKeeper.Models
{
    public partial interface ITimeKeeperDBContextProcedures
    {
        Task<List<TiemposEmpleadoByDateResult>> TiemposEmpleadoByDateAsync(DateTime? fechaIni, DateTime? fechaFin, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
