// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TimeKeeper.Models
{
    public partial class Tiempos
    {
        public int IdTime { get; set; }
        public int IdEmpleado { get; set; }
        public DateTime Fecha { get; set; }
        public TimeSpan Tiempo { get; set; }

        public virtual Empleados IdEmpleadoNavigation { get; set; }
    }
}